# Site settings
baseurl: ""
url: "https://cv-olio.netlify.com"
pattern-style: candy-b
pattern-background: darkslategray
pattern-foreground: cyan
pattern-size: 5
language: en
#seo: true

# Personal settings
owner: Terry Gilliam
github: gisforgabriel
email: terry.gilliam@gmail.com
telephone: +44 (0)207 123 4568
address: Highgate, London, UK N6 1MP

# Build settings
exclude: ["ReadMe.md", "Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: _sass
collections:
  portfolio_items:
  cv_items: