# Site settings - leave values empty if not required
owner: Terry Gilliam
github: gisforgabriel
baseurl: "/CV-olio/"
url: "https://gisforgabriel.github.io/"
# Choose `pattern-style` from: china-a, lines-a, lines-b, lines-c, lines-45-a, lines-45-b, lines-45-c, cross-a, cross-b, cross-c, cross-thin-a, cross-thin-b, cross-thin-c, candy-a, candy-b, candy-c (not working), feather
pattern-style: candy-b
pattern-background: darkslategray
pattern-foreground: cyan
pattern-size: 5
#seo: true

# Build settings
exclude: ["ReadMe.md", "Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: _sass
collections:
  portfolio_items:
  cv_items: